# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET 7.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Setup .NET 8.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: List installed .NET SDKs
      run: dotnet --list-sdks
        
    - name: Display dotnet version
      run: dotnet --version
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build the project
      run: dotnet build --configuration Release --no-restore
      
    - name: Run test
      run: dotnet test --configuration Release --no-build --verbosity normal
